export const User = [
    {
      id: 1,
      name: {
        firstname: "DARWIN",
        lastname: "PATAC",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "DARDAR",
      password: "4545",
      usertype: "STUDENT",
    },
    {
      id: 2,
      name: {
        firstname: "JOHN CARLO",
        lastname: "RAZON",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "WAMPYB",
      password: "1500",
      usertype: "STUDENT",
    },
    {
      id: 3,
      name: {
        firstname: "JESS",
        lastname: "JUMAWAN",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "KAP",
      password: "6969",
      usertype: "STUDENT",
    },
    {
      id: 4,
      name: {
        firstname: "JOHN MARK",
        lastname: "LAGRIMAS",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "JOHN",
      password: "3233",
      usertype: "STUDENT",
    },
    {
      id: 5,
      name: {
        firstname: "JOVERT",
        lastname: "DAVIRAO",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "BATMAN",
      password: "5555",
      usertype: "STUDENT",
    },
    {
      id: 6,
      name: {
        firstname: "JAMES",
        lastname: "NOBLE",
      },
      course: "BSIT",
      yearsection: "3B",
      username: "JAMIS",
      password: "2322",
      usertype: "STUDENT",
    },
    {
      id: 7,
      name: {
        firstname: "JERRY",
        lastname: "ALE",
      },
      course: "",
      yearsection: "",
      username: "JERRY",
      password: "8722",
      usertype: "TEACHER",
    },
    {
      id: 8,
      name: {
        firstname: "GABRENE",
        lastname: "DIAZ",
      },
      course: "",
      yearsection: "",
      username: "GABRENE",
      password: "7888",
      usertype: "TEACHER",
    },
    {
      id: 9,
      name: {
        firstname: "FERMO",
        lastname: "ASUFRA",
      },
      course: "",
      yearsection: "",
      username: "FERMO",
      password: "5699",
      usertype: "TEACHER",
    },
    {
      id: 10,
      name: {
        firstname: "WENZEAL",
        lastname: "AGOC",
      },
      course: "",
      yearsection: "",
      username: "WENZEAL",
      password: "8710",
      usertype: "TEACHER",
    },
    
  ];